### ISSUE TITLE
Making available on conda-forge

### ISSUE THREAD

**Issue by jackirvine97** [smarie/python-pytest-cases#135]
I'm using pytest-cases on a number of projects destined to be made available on conda-forge as well as PyPI. I'm currently stuck in doing this because having a dependency that isn't available itself on conda-forge blocks the build process. I'd like pytest-cases to be available on conda-forge.

Would this be possible?

Thanks for making a really useful tool!

**Comment by smarie** [comment]
Thanks @jackirvine97 for the kind words and the proposal.

I am not at all against publishing in conda forge and I think that 

On a side note, I saw pyproprop: on the same have you tried [pyfields](https://smarie.github.io/python-pyfields/)+autoclass+vtypes(optional), or attrs, or pydantic ? Just in case you do not know these projects. There are so many libs achieving this goal already that seeing yet a new one is a bit sad :)

**Comment by jackirvine97** [comment]
Thanks @smarie! Let me know how you get on/if you need any help on this!

And thanks for pointing out - I'll be sure to checkout those libs.

**Comment by smarie** [comment]
@jackirvine97 small message to let you know about my progress. I created the PR to publish `makefun` on conda forge today: https://github.com/conda-forge/staged-recipes/pull/12830

Then I'll do `decopatch` and finally `pytest-cases`.
Kind regards

**Comment by jackirvine97** [comment]
Brilliant, thanks for the update!

**Comment by smarie** [comment]
Hi @jackirvine97 , quick update on this topic. I was able to make `makefun` (one of pytest-cases dependencies) available on conda-forge. However after a bit of thinking I do not feel that this is right, and I even plan to remove it. 

Indeed, publishing a package on conda-forge is really only interesting if the package has some binary (cython) part. Otherwise, if this is a pure python wheel, I do not see any reason why people would not rely on PyPi repo, as we all do already. Does that make sense ? Do not hesitate to share your thoughts here. Thanks !

**Comment by brocksam** [comment]
Hi @smarie, thanks very much for your update. I'm replying on behalf on @jackirvine97 as he's no longer actively working on the project in which we're using pytest-cases. I think the key point for me here is that pip/PyPI and conda/conda-forge serve two different purposes (although here they appear to overlap significantly). It's probably best explained with an example:

I have a Python package which has dependencies on non-Python code. If all dependencies are available on conda-forge then the package can easily be installed in a conda-env using conda, great! If version requirements of dependencies change then these can be resolves in the conda-env easily by conda as conda is tracking all of the dependencies, not just the pure-Python ones. This type of situation necessitates the use of conda/conda-forge over pip/PyPI and is not uncommon when the package in question is scientific (NumPy, SciPy, Matplotlib etc. all have non-Python dependencies).

If one of the dependencies is not available on conda-forge then it can be installed using pip, fine. The problems occur when then trying to upgrade packages within the conda-env that pip has been used in to install something else. As the pip-installed package isn't being tracked properly by conda it can likely give rise to dependency conflicts which aren't correctly resolved, breaking the conda-env. The solution is that every time a version needs updating then conda-env is retired and dependencies installed from scratch again with the pip-only ones done last. Another issue is that if you want to distribute your package on conda-forge, all of the dependencies are required to be on conda-forge too (as we've seen here). The test suite is run in the conda recipe and so if the test suite depends on pytest-cases then that's a road block to publishing to conda-forge.

If you need to use conda/conda-envs instead of pip/venvs it's possible to work with packages that aren't on conda-forge, it's just more hassle than if they are. I've got a non-pure-Python package that I'm just about to release which has dependencies on C/C++ binaries, Cython code and currently depends on pytest-cases for its test suite. Given the choice between using pytest-cases and publishing on conda-forge I'd have to go with the later, although I'd rather not as pytest-cases has been great to use and I very much appreciate it!

I realise that being the first to bring this up means that it's a reasonable niche use case, and so I completely understand if you don't agree with me here and wish to remove makefun etc. from conda-forge. Thanks 🙂

**Comment by smarie** [comment]
Thanks @brocksam ! So if I understand correctly, you can **not** publish your package on conda-forge if it has a test dependency (pytest-cases) that is not on conda forge ?

**Comment by brocksam** [comment]
I've double checked with conda-forge and the dependencies (even test dependencies) do need to be on conda-forge for the test suite to be run as part of the build process. However, in this case I can get round pytest-cases not being on conda-forge by just skipping running the test suite in that part of the build process (which is apparently pretty common).

> This is very surprising to me that people at conda did not think about this use case

I think the consensus is that because multiple packages can be added at once (see: https://conda-forge.org/docs/maintainer/adding_pkgs.html#adding-multiple-packages-at-once) and because packages already on PyPI are trivial to add to conda-forge using Grayskull (see: https://github.com/conda-incubator/grayskull) that if any dependencies are not currently on conda-forge then they can just be bundled in when adding the downstream package.

**Comment by smarie** [comment]
Oh, sad to see this multi-package feature just now :(

I added https://github.com/conda-forge/staged-recipes/pull/13337
and https://github.com/conda-forge/staged-recipes/pull/13342

So that should be done soon

**Comment by brocksam** [comment]
Thank you very much @smarie! You've been an excellent help!

**Comment by smarie** [comment]
It seems to be available: https://github.com/conda-forge/pytest-cases-feedstock

@brocksam can you please check and let me know so that I can then close the ticket ? Thanks !

**Comment by brocksam** [comment]
Thank you @smarie! I've tested pytest-cases from conda-forge this morning, both locally and on CI and it's working properly. That's such a great help, thank you very much. Please go ahead and close the issue 🙂

**Comment by smarie** [comment]
Perfect thanks @brocksam  !
