### ISSUE TITLE
paramterize_plus runs fixtures even if they should be skipped

### ISSUE THREAD

**Issue by pehala** [smarie/python-pytest-cases#137]
If you use `pytest.param `with `fixture_ref`, the referenced fixtures will be run even if they should be skipped due to `pytest.mark.skipif`
```python
import pytest
from pytest_cases import fixture_plus, parametrize_plus, fixture_ref


@fixture_plus(scope="module")
def a():
    print("a")
    return "a"


@fixture_plus(scope="module")
def b():
    print("b")
    return "b"


@parametrize_plus("fixture", [pytest.param(fixture_ref(a), marks=pytest.mark.skipif("1 > 0")),
                              pytest.param(fixture_ref(b))])
def test(fixture):
    print(f"Test ran fixure {fixture}")
```
Result:
```
SKIPPED                                      [ 50%]
Skipped: condition: 1 > 0
a
b
PASSED                                       [100%]Test ran fixure b
```
Tested on:
pytest-cases: 2.2.2
pytest: 6.0.2

**Comment by smarie** [comment]
Thanks for reporting @pehala ! This is strange indeed. I'll have a look next week - not a lot of bandwidth these days :(

**Comment by smarie** [comment]
Ok so this is related to the scope of the fixtures: if they use function scope the bug does not appear. (Note that you can use the new names `fixture` and `parametrize` instead of the `..._plus` form):

```python
import pytest
from pytest_cases import fixture, parametrize, fixture_ref

@fixture(scope="function")
def a():
    print("a")
    return "a"

@fixture(scope="function")
def b():
    print("b")
    return "b"

@parametrize("fixture", [pytest.param(fixture_ref(a), marks=pytest.mark.skipif("1 > 0")),
                         pytest.param(fixture_ref(b))
                         ])
def test(fixture):
    print("Test ran fixure %s" % fixture)
```

**Comment by smarie** [comment]
This issue comes from the fact that since fixture unions are not actually handled by the pytest fixture engine, I "cheat" to deactivate them by adding a parameter to them containing a key symbol `NOT_USED`. Doing so when the fixture is functions-scoped is ok, because the fixture would anyway be recreated the next time it is needed. However, doing so for session- or module-scoped fixtures forces pytest to recreate them when it is not needed. This is why currently I do not do this. A consequence, as you found out, is that a module-scoped fixture used in a union will always be called the first time that union is used.

I'll try to find a more clever hacky workaround, but I'm clearly reaching the limits of what can be done without changing the pytest engine here..

**Comment by smarie** [comment]
@pehala I turned the problem in my head for a while and did several tests, and as a conclusion I think that this is not something I will be able to fix, unfortunately :( .

Indeed I only found two ways to fix this:

 - either by doing for session- and module-scoped fixtures the same thing that I do already for function-scoped fixtures. That is, adding them a NOT_USED parameter when they are not used by a specific test node because it belongs to a leaf in the fixture closure tree that does not use that fixture. This has a big side-effect: if the fixture should be (and could be) unique across the whole session or module, then it can become created several times, for no good reason. The test [here](https://github.com/smarie/python-pytest-cases/blob/master/pytest_cases/tests/pytest_extension/fixtures/fixture_unions/test_fixture_union_setup_teardown3.py) for example breaks with this fix.

 - or I could inspect all calls and determine for each of them if there is a skip/fail mark, so as to determine for each fixture with session and module scope that is not used in all fixture tree leaves, if they are going to be skipped or not and therefore if there is one remaining. I created that code [here]() but had to comment it out because pytest does not currently evaluate skip/skipif/fail marks on CallSpec objects, but on test items. So I can not easily create the function [is_skipped_or_failed(callspec)](https://github.com/smarie/python-pytest-cases/blob/3167c475f7641667d92f1e06908d318c8b6196fb/pytest_cases/plugin.py#L963). If you find a way to do this do not hesitate to let me know.

For reference this is what pytest does to determine if an item is skipped: [this hook](https://github.com/pytest-dev/pytest/blob/b250c9d6157fe6ae6d308d0fbd7625b280b793fc/src/_pytest/skipping.py#L233) is called and relies on `evaluate_skip_marks(item)` to perform all evaluations. My problem is that when I can act, I do not have this `item`, I only have callspecs. So I would be able to detect unconditional skip marks and failures, but not conditional ones - or at least I would need to reimplement the evaluation procedure... Besides I do not even know if that would be enough to catch other marks ending on the item but not being passed through the callspec (the pytest.param that you use). So this does not feel right, really.
