### ISSUE TITLE
request.getfixturevalue('somevalue') returns lazyvalue

### ISSUE THREAD

**Issue by TheCaffinatedDeveloper** [smarie/python-pytest-cases#143]
I often use a pattern of performing some additional setup via another fixture by using the "special" request object to introspect the current test method. Once scenario involves using the request.getfixturevalue('foo') which should return the actual value being used in the current context but with pytest_cases I get the lazy object and have to call the .get() to get the value. 

The problem is that I am not always using pytest_cases and would like my fixtures to be common and reused where it might not be a lazy object and thus not have a .get method. Perhaps I am doing something wrong, guidance requested please.

**Comment by smarie** [comment]
Hi @TheCaffinatedDeveloper ! The principle of `pytest_cases` is that you create many case functions, that are used to parametrize your test function. Since case functions can take some time to execute and be memory consuming, I chose to follow the pattern that `pytest` uses everywhere else, that is, to execute these functions just when they are needed - exactly what happens with function-scope fixtures. This is why I use `lazy_value` to have them be called just before usage. See [documentation](https://smarie.github.io/python-pytest-cases/pytest_goodies/#parametrize) for details.

One way to solve your issue is to use duck typing (`try: val.get(); except AttributeError: pass`) or to rely on `is_lazy`:

```python
from pytest_cases.common_pytest_lazy_values import is_lazy

val = request.getfixturevalue('foo')
if is_lazy(val):
    val = val.get()
```

Note that I consider adding `is_lazy` to the official API (so that you can directly import from pytest_cases), do you think that this could be a good idea ?

**Comment by smarie** [comment]
I have an afterthought here: currently `_LazyValue` does not have a cache mechanism as opposed to `LazyTuple`/`_LazyTupleItem`. So your `get()` call would trigger an *additional* call to the case function, instead of just calling it *earlier*.
I could quite easily add such a cache in a next version, following what I did in `LazyTuple`.

**Comment by TheCaffinatedDeveloper** [comment]
@smarie Thank you for your timely response and suggestions. I was thinking of checking for the lazy items adhoc but was unaware of the is_lazy method - thank you for pointing me in that direction. I think it is worthwhile adding it to the official api. The current project I work on uses the test method doc string to update test descriptions (that get synced to a cloud requirements tool) during a "setup" phase and I am now parametrizing this doc_string using some of the values from the parameters being passed in via a fixture. Others may be doing the same or want to which is why I think adding it to the api would be worthwhile :) 

PS. I hope pytest-cases gets incorporated into pytest core and you become rich and famous :)

**Comment by TheCaffinatedDeveloper** [comment]
> I have an afterthought here: currently `_LazyValue` does not have a cache mechanism as opposed to `LazyTuple`/`_LazyTupleItem`. So your `get()` call would trigger an _additional_ call to the case function, instead of just calling it _earlier_.
> I could quite easily add such a cache in a next version, following what I did in `LazyTuple`.

Great point, this would stay in line with only needing to call the TC function once and the second call would simply retrieve the value from cache - nice!

**Comment by smarie** [comment]
Cool @TheCaffinatedDeveloper thanks for the feedback. I'll do my best when I have some bandwidth again - for now I am in paternity leave so my dev time is fairly limited as you can imagine

> I hope pytest-cases gets incorporated into pytest core and you become rich and famous :)

:D if open source development was a path to fame and money we would all know it by now :) but I appreciate your kind words and positive feedback, this is a far better reward !

**Comment by smarie** [comment]
@TheCaffinatedDeveloper this will ship with 2.4.0 probably topday when travis wakes up : it seems to be extremely slow these days
