### ISSUE TITLE
Support for "online" case generation

### ISSUE THREAD

**Issue by plammens** [smarie/python-pytest-cases#161]
Currently there seems to be no support for "online" test case generation (correct me if I'm wrong), i.e. generating test cases *in function of* any sub- parameters, other cases, or fixtures the case function might be dependent on.

For example, suppose we have a `foo` fixture which has (the returned fixture, not the function) an iterable attribute `attr`, and we want to generate every possible pair of items from `foo.attr` (i.e. `itertools.combinations(foo.attr, r=2)`). Currently there's no way to do this since the only form of case generators is "offline", i.e. where the set of individual test cases is computed at test collection and hence can't depend on fixtures or parameters.

I would say this would be a very useful feature. What do you think? Would there be a "natural" way of implementing this without interfering with current features?

An implementation idea would be to add a parameter to the `case` decorator that indicates that the function is such a generator, and let the case function return an iterable/Python generator, e.g.:
```python
@pytest_cases.case(generator=True)
def case_pair(foo):
    yield from itertools.combinations(foo.attr, r=2)
```

**Comment by smarie** [comment]
Thanks @plammens ! Unfortunately this falls into the now "classical" pytest pitfall: it is not possible by design in `pytest` to use the contents of a fixture to parametrize tests, because the list of all tests nodes has to be known in advance (i.e. BEFORE the fixtures are evaluated) by pytest.

See [this stackoverflow answer](https://stackoverflow.com/questions/42228895/how-to-parametrize-a-pytest-fixture/56871701#56871701).

Feel free to reopen if I misunderstood and this answer does not apply to your proposal
