### ISSUE TITLE
Why do I need fixture_ref?

### ISSUE THREAD

**Issue by kousu** [smarie/python-pytest-cases#177]
Hi! Thanks for your work on pytest-cases. It's really great to see innovation in making expressivity better for testing. Maybe kind of a dry topic for some, but I'm into it right now :P

So here's my deal, I want this to work:

```
@pytest.fixture
def a():
   return "a"*int(os.environ["N"])

@pytest.fixture
def b():
   return "b"*int(os.environ["M"])

@pytest.mark.parameterize("letters", [a,b])
@pytest.mark.parameterize("order", [True, False])
def test_stuff(letters, order):
    if not order:
        letters = letters[::-1]
    assert letter.upper() == letter.lower().upper()
```

This doesn't work, of course, because pytest doesn't support mixing @parametrize and fixtures. That's what led us to find pytest-cases in the first place, and it does, but I need to write:

```
@pytest.mark.parameterize("letters", [fixture_ref(a),fixture_ref(b)])
```

Is it possible to detect this situation automatically? Passing `a` without `fixture_ref` around it just crashes so it doesn't seem to be doing anything meaningful at the moment.

**Comment by kousu** [comment]
I've written this little wrapper and it seems to do exactly what I want:

```
def parametrize(argnames=None,
                argvalues=None,
                *args, **kwargs):
    """
    Wrap pytest_cases.parametrize (which wraps pytest.mark.parametrize)
    to avoid having to repeat fixture_ref() everywhere.

    See https://smarie.github.io/python-pytest-cases/api_reference/#parametrize
    """
    return pytest_cases.parametrize(argnames,
                                    [(pytest_cases.fixture_ref(v) if hasattr(v,'_pytestfixturefunction') else v)
                                      for v in argvalues] if argvalues else argvalues,
                                    *args,
                                    **kwargs)
```

You can see [it](https://github.com/neuropoly/spinalcordtoolbox/blob/7bbce7ab7c113c0d9725fdf7ab8406ea432a9ae7/unit_testing/test_utils.py#L13-L27) in use at https://github.com/neuropoly/spinalcordtoolbox/blob/7bbce7ab7c113c0d9725fdf7ab8406ea432a9ae7/unit_testing/test_reports.py#L46-L62 and passing a test at https://travis-ci.com/github/neuropoly/spinalcordtoolbox/jobs/472955917#L1424

**Comment by smarie** [comment]
This is a great idea @kousu . Indeed, when the fixture symbol is locally available this makes sense to detect it automatically.

Would you like to open a PR for this or would you like me to do it ? Note that instead of your explicit test I'll ask you to use `is_fixture` (from `.common_pytest` module). As always tests (under tests/pytest_extension/parametrize_plus) and docs (pytest_goodies.md and api_reference.md) should be updated accordingly.

**Comment by kousu** [comment]
Awesome, I'm glad I was on the right track. Yes, I would like to take that on :)

It might take me a bit to figure out how to slot it into the codebase. I am also wondering if there are any caveats (like maybe conflicts with `lazy_value`?) that prevented this in the first place.

**Comment by smarie** [comment]
The method that you want to modify is [`_process_argvalues`](https://github.com/smarie/python-pytest-cases/blob/a9083f2195714c49e5606b5191c6fe26d298a691/pytest_cases/fixture_parametrize_plus.py#L1139)

As you'll see it performs some processing on the values tested with `isinstance(v, fixture_ref)`. So you'll want to replace fixtures by a fixture reference just before these checks so that the actions are taken similarly. You'll have to replace it both in `argvalues` and `marked_argvalues` (as done here: https://github.com/smarie/python-pytest-cases/blob/a9083f2195714c49e5606b5191c6fe26d298a691/pytest_cases/fixture_parametrize_plus.py#L1246) as any of the two might be used subsequently.

Since this part of the code is not very straightforward, do not hesitate to let me know if you eventually find that it would take too much time to get right. I can definitely understand since this part is quite unelegantly coded, sorry for that :(.

**Comment by smarie** [comment]
Hi @kousu , I was in a refactoring today for other issues, so I decided to take a stab at it considering the above comment where I realize that it creates quite a barrier to entry in the code. 

I hope that you did not spend too much time on it since my last message!
