### ISSUE TITLE
Make the CI workflow execute the tests based on installed package, not source

### ISSUE THREAD

**Issue by smarie** [smarie/python-pytest-cases#222]
As pointed out in https://github.com/smarie/python-pytest-cases/issues/220

The nox and CI build currently run the tests against the source, not the installed package. This is not nice, as it could miss some packaging issues.

In order to make this move, we would need the `tests/` folder to be outside of the `pytest_cases` folder, otherwise an import issue happens as noted by @kloczek in #220. This is due to the fact that `pytest` has a package auto-detection mechanism recursively climbing up the folders above `conftest.py` and stopping at the last `__init__.py`.

Let's take some time to figure out if this is the **ONLY** way to go ?

**Comment by kloczek** [comment]
So looks like it would be good to contact nox maintainer ..🤔 (?)

PS. FYI I'm trying to use everywhere pytest instead tox and other because I'm building my packages in dedicated system created only to build exact package in which are installed only build dependencies listed in rpm spec file co wrapping for example test suite and install for example nox or tox does not make to much sense.

**Comment by smarie** [comment]
Hi @kloczek 

I tried to fix this by moving to the reference structure described [here](https://docs.pytest.org/en/6.2.x/goodpractices.html#tests-outside-application-code). 

The PR is here #232, would you mind letting me know if this fixes your issue ?
