### ISSUE TITLE
Assistance with @parametrize

### ISSUE THREAD

**Issue by wonboyn** [smarie/python-pytest-cases#237]
Hi there,

I am trying to generate a bunch of cases from a function using the following:

```python
@parametrize(task=get_tasks())
def case_task(self, task):
   return task`
```

I have this working without issue when get_tasks() returns a list of strings. 
However, in my scenario the get_tasks() returns a list of objects. 

What I'm trying to achieve is one case per object (from the list returned by get_tasks()) and to use the object.name property as the case id

Any guidance on how to do this would be greatly appreciated.

Thanks

Tim

**Comment by smarie** [comment]
Thanks @wonboyn !

You can provide a callable to `ids` or to `idgen` in order to create the test node id. The difference between the two is what happens when there is a tuple of parameters:

 - `ids` will be called for each parameter separately
 - `idgen` will be called with all parameters, as keyword arguments

So the following works:

```python
from pytest_cases import parametrize, parametrize_with_cases

class Person:
    def __init__(self, name):
        self.name = name

def get_tasks():
    return [Person("joe"), Person("ana")]

class CasesFoo:
    @parametrize(task=get_tasks(), idgen=lambda task: task.name)
    def case_task(self, task):
        return task

@parametrize_with_cases("task", cases=CasesFoo)
def test_foo(task):
    print(task)

```

**Comment by wonboyn** [comment]
Thanks @smarie. The example above using idgen did exactly what I wanted.

**Comment by smarie** [comment]
Great ! Thanks for the feedback @wonboyn
