### ISSUE TITLE
Support default test cases

### ISSUE THREAD

**Issue by saroad2** [smarie/python-pytest-cases#96]
I would like to be able to use the `cases_data` decorator without the need to specify the cases every time.

consider the following test module:

```python
from pytest_cases import CaseData, cases_data


def case_one_plus_one() -> CaseData:
    inp = [1, 1]
    output = dict(sum=2, diff=0)
    return inp, output, None


def case_three_plus_four() -> CaseData:
    inp = [4, 3]
    output = dict(sum=7, diff=1)
    return inp, output, None


@cases_data()
def test_sum(case_data):
    (a, b), out, _ = case_data.get()
    assert a + b == out["sum"]


@cases_data()
def test_diff(case_data):
    (a, b), out, _ = case_data.get()
    assert a - b == out["diff"]

```

As you can see, In this example the cases should be taken by default **from the current test module**, if it wasn't specified otherwise.

This will clean a lot of the boilerplate code you are trying to avoid by using `parameterized_plus`.

Personally, I don't like the `pytest.mark.parameterize` approach very much. I prefer your original approach of test cases much better!

What do you think about my proposal? If you approve, I'll go ahead and implement it.

**Comment by smarie** [comment]
Thanks for the proposal and kind words :) And thanks for the feedback about the easier-to-read decorators than pytest.mark.parametrize.

Did you try `@cases_data(module=THIS_MODULE)` ? (you need to import THIS_MODULE from pytest_cases)

Otherwise, I agree on the boilerplate, however the current plan was to have as default the file named `test_xxx_cases.py` (see #91 ). Obviously I will keep the `THIS_MODULE` option. Would that seem ok to you ?

Finally note that I am currently moving towards v2 where case functions will, while still having user-friendly decorators, be as flexible as pytest fixtures and tests (cases will be able to use fixtures for examples, such as a database connection). See #90

**Comment by saroad2** [comment]
Hey, thank you very much for the answer! After I published this issue, I found out about `THIS_MODULE`.

In any case, #91 will solve the entire problem! Take a look there and see that I've suggested a new pattern for the cases path. I think it will be much better.

**Comment by smarie** [comment]
Thanks @saroad2 . I answer in #91 . I'll close this one, please feel free to reopen if needed
